[package]
name = "constructing_lp"
version = "0.1.0"
edition = "2024"

[dependencies]
pyo3 = { version = "0.21", features = ["extension-module"] }
serde = { version = "1.0.204", features = ["derive"] }
serde_json = "1.0.120"
sprs="0.11.3"